---
languages:
  Ruby: true
  JavaScript: true
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
